config/routes.rb
Rails.application.routes.draw do
	resources :patients
	root "patients#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :patient_labs, dependent: :destroy
	validates_presence_of :id_number
end

app/models/patient_lab.rb
class PatientLab < ApplicationRecord
	belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def index
		@patients = Patient.all
	end

	def create
		lab_data = LaboratoryApiService.new.call(params)
		CreatePatientLabService.new.call(lab_data)

		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails6PatientTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<%= link_to "Get record from 1st lab", patients_path(case1: "case1"), method: :post %><br>
<%= link_to "Get record from 2nd lab", patients_path(case2: "case2"), method: :post %>

<h1>All Patients</h1>
 
<div class="container">
  <div class="row">
  <% @patients.each do |patient| %>
    <div class="col-sm-6 mb-4">
      <div class="card">
        <div class="card-header">
        <h5>Patient Details</h5>
         <p>ID: <%= patient.id_number %></p>
         <p>Name: <%= patient.patient_name %> </p>
         <p>Gender: <%= patient.gender %></p>
        </div>
        <div class="card-body">
          <h5>Patient Lab</h5>
        <% patient.patient_labs.each do |patient_lab| %>
          <p>Code: <%= patient_lab.code %></p>
          <p>Lab: <%= patient_lab.name %></p>
          <p>Unit: <%= patient_lab.unit %></p>
          <p>Ref Range: <%= patient_lab.ref_range %></p>
          <p>Finding: <%= patient_lab.finding %></p>
          <p>Result State: <%= patient_lab.result_state %></p>
          <p>Lab Number: <%= patient_lab.lab_number %></p>
          <p>Clinic code: <%= patient_lab.clinic_code %></p>
          <p>Date of test: <%= patient_lab.date_of_test %></p>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>